### ISSUE TITLE
webclip not working: Uncaught DOMException

### ISSUE THREAD

**Issue by chymian** [vrtmrz/obsidian-livesync-webclip#4]
Livesync is up and runing on div. devices.
webclip throws errors on use, see below:

db.adr: https://domain.tld:port/database-name/
webclip folder created in vault
browser: Version 104.0.5112.102 (Official Build, ungoogled-chromium) built on Debian bullseye/11, running on Debian bullseye/11 (64-Bit)

any hints?

Errors:
```
vendor.js:2 Uncaught (in promise) DOMException: Failed to read the 'result' property from 'IDBRequest': The request has not finished.
    at Gr.e._destroy (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:79794)
    at i (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:41263)
    at chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:41489
Gr.e._destroy @ vendor.js:2
i @ vendor.js:2
(anonymous) @ vendor.js:2
vendor.js:2 Uncaught (in promise) DOMException: Failed to read the 'result' property from 'IDBRequest': The request has not finished.
    at Gr.e._destroy (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:79794)
    at i (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:41263)
    at chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:41489
Gr.e._destroy @ vendor.js:2
i @ vendor.js:2
(anonymous) @ vendor.js:2
Promise.then (async)
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
Ft.execute @ vendor.js:2
Ft.ready @ vendor.js:2
(anonymous) @ vendor.js:2
Ur @ vendor.js:2
e @ vendor.js:2
(anonymous) @ vendor.js:2
h.run @ vendor.js:2
c @ vendor.js:2
vendor.js:2 Uncaught (in promise) DOMException: Failed to read the 'result' property from 'IDBRequest': The request has not finished.
    at Gr.e._destroy (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:79794)
    at i (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:41263)
    at chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:41489
Gr.e._destroy @ vendor.js:2
i @ vendor.js:2
(anonymous) @ vendor.js:2
Promise.then (async)
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
Ft.execute @ vendor.js:2
Ft.ready @ vendor.js:2
(anonymous) @ vendor.js:2
Ur @ vendor.js:2
e @ vendor.js:2
(anonymous) @ vendor.js:2
h.run @ vendor.js:2
c @ vendor.js:2
vendor.js:2 Uncaught (in promise) DOMException: Failed to read the 'result' property from 'IDBRequest': The request has not finished.
    at Gr.e._destroy (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:79794)
    at i (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:41263)
    at chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:41489
Gr.e._destroy @ vendor.js:2
i @ vendor.js:2
(anonymous) @ vendor.js:2
Promise.then (async)
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
(anonymous) @ vendor.js:2
Ft.execute @ vendor.js:2
Ft.ready @ vendor.js:2
(anonymous) @ vendor.js:2
Ur @ vendor.js:2
e @ vendor.js:2
(anonymous) @ vendor.js:2
h.run @ vendor.js:2
c @ vendor.js:2
```

**Comment by vrtmrz** [comment]
Really sorry for being too late, I did not notice everything on this repo.
This message is still shown, but things would be getting better on 0.0.4.
This problem has been fixed on 0.0.4! I submitted the new version for review. 
Could you please try 0.0.4 after it is approved?

**Comment by chymian** [comment]
tested it with 0.4. today with no luck.

```
libs.min.js?legacy:1 JQMIGRATE: Migrate is installed, version 3.3.2
vendor.js:2 Uncaught (in promise) DOMException: Failed to read the 'result' property from 'IDBRequest': The request has not finished.
    at Gr.e._destroy (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:79989)
    at i (chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:40683)
    at chrome-extension://jfpaflmpckblieefkegjncjoceapakdf/js/vendor.js:2:40909
Gr.e._destroy @ vendor.js:2
i @ vendor.js:2
(anonymous) @ vendor.js:2
```

**Comment by allFunAndGames** [comment]
Just to confirm, not just OP, I have the same issue with the same error message

**Comment by chymian** [comment]
@vrtmrz 

did you abonden the webcilpper, or is it still supported?

**Comment by vrtmrz** [comment]
Sorry for being late! I did not abandon this project, but not mainly used and just for a simple lack of time.
(It is also the same situation on FileSystem-LiveSync and some, however, they just still keep compatible).
I hope to make it work again.
